base-urls:
  idam-user: ${IDAM_API_URL:http://localhost:4501}
  idam-s2s: ${S2S_URL:http://localhost:4502}
  s2s-token: ${S2S_TOKEN:AAAAAAAAAAAAAAAA}
  test-url: ${TEST_URL:http://localhost:8080}

#this need to be removed
info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:coh}
    name: ${PACKAGES_NAME:cor}